version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=ai_chat
      - SECRET_KEY=your-secret-key-here
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - chroma_data:/app/chroma_db
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_chat
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  chroma_data:
